import { supabaseAdmin } from "../utils/supabase.client";
import { QueryFragments } from "../constants/queryFragments";
import {
  CustomerApprovedRedemption,
  CustomerApprovedRedemptionPage,
  CustomerPendingRedemption,
  CustomerRedemptionRequestBody,
  CustomerRedemptionRequestResult,
} from "../types/customerRedemptions.types";

// ────────────────────────────────────────────────────────────────────────────
// Service
// ────────────────────────────────────────────────────────────────────────────

/**
 * Customer-app redemption-request service — backs the customer-side
 * redemption endpoints:
 *
 *   GET    /customers/me/merchants/:merchantId/branches
 *   GET    /customers/me/merchants/:merchantId/redemptions/pending
 *   POST   /customers/me/merchants/:merchantId/redemptions
 *   PATCH  /customers/me/merchants/:merchantId/redemptions
 *   DELETE /customers/me/merchants/:merchantId/redemptions
 *
 * The row-based model: there's at most one `customer_credit_redemptions`
 * row per (customer, merchant) pair in the pending state. The row
 * carries a 4-digit code that's generated by the SQL RPC on create /
 * edit. Cancel hard-deletes the row.
 *
 * All writes go through SQL RPCs (`redemption_request_create`,
 * `redemption_request_update`, `redemption_request_cancel`) so the
 * audit-row write + fan-out happen atomically server-side. Reads use
 * the typed Supabase client — no `any` / `as` casts on the Supabase
 * builders or results.
 */
export class CustomerRedemptionsService {
  // ──────────────────────────────────────────────────────────────────────────
  // Queries
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * List non-deleted branches at a merchant — drives the redemption
   * sheet's branch picker. The customer app calls this once per
   * merchant detail screen and caches it; the list is small (≤ a
   * handful of branches).
   */
  async getMyBranches(merchantId: number) {
    const { data, error } = await supabaseAdmin
      .from("branches")
      .select(QueryFragments.BASE_BRANCH)
      .eq("merchant_id", merchantId)
      .is("deleted_at", null)
      .order("name", { ascending: true });
    if (error) {
      throw new Error(`Failed to load branches: ${error.message}`);
    }
    return data ?? [];
  }

  /**
   * Read the customer's pending redemption at one merchant (the
   * audit-row projection). Returns `null` when no pending row exists
   * — the route layer always resolves, never 404s on "no pending".
   *
   * Carries the 4-digit `redemption_code` so the customer can show
   * the code on the Pending tab. The merchant app MUST NOT see this
   * code — the merchant service reads the audit row directly but
   * strips `redemption_code` from its response.
   */
  async getMyPendingRequest(
    customerId: number,
    merchantId: number,
  ): Promise<CustomerPendingRedemption | null> {
    const { data, error } = await supabaseAdmin
      .from("customer_credit_redemptions")
      .select(
        `id, customer_id, merchant_id, branch_id, amount_redeemed, redemption_code, requested_date, created_at, branch:branches(${QueryFragments.BASE_BRANCH})`,
      )
      .eq("customer_id", customerId)
      .eq("merchant_id", merchantId)
      .is("deleted_at", null)
      .is("approved_at", null)
      .is("rejected_at", null)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (error) {
      throw new Error(`Failed to load pending request: ${error.message}`);
    }
    if (!data) return null;

    // Cast the nested branch join into the right shape — Supabase infers
    // a wide row type that includes the join. We pull only the fields
    // the customer-facing view needs.
    const branch = data.branch as unknown as {
      id: number;
      name: string | null;
    } | null;

    return {
      redemption_code: Number(data.redemption_code),
      redemption_id: Number(data.id),
      branch_id: Number(data.branch_id),
      branch_name: branch?.name ?? null,
      amount_redeemed: Number(data.amount_redeemed),
      requested_date: Number(data.requested_date),
      requested_at: String(data.created_at),
    };
  }

  /**
   * List the customer's approved redemptions at one merchant — drives
   * the merchant-screen "Approved" tab. One row per approved request
   * (the audit-trail projection, NOT the per-credit slice rows).
   *
   * Cursor-paginated by `approved_at DESC`. The caller passes the last
   * item's `approved_at` (ms) as `cursor`; the service filters with
   * `approved_at < cursor` so rows are strictly older than the previous
   * page. `limit` is clamped to [1, 50] with a default of 20.
   *
   * `nextCursor` is the last row's `approved_at` (ms) when the page
   * came back exactly `limit`-sized — i.e. the caller should keep
   * fetching. `null` when the page was partial or empty (end-of-feed).
   *
   * The 4-digit code is intentionally NOT returned — the code was used
   * once at approve time and is no longer needed for reference. Customer
   * privacy: the merchant side has its own list (see the webapp's
   * `Redemptions.tsx`) which excludes the code.
   */
  async getMyApprovedRedemptions(
    customerId: number,
    merchantId: number,
    params: { cursor?: number; limit: number },
  ): Promise<CustomerApprovedRedemptionPage> {
    const limit = Math.min(Math.max(1, params.limit), 50);
    let query = supabaseAdmin
      .from("customer_credit_redemptions")
      .select(
        `id, branch_id, amount_redeemed, approved_at,
         branch:branches(${QueryFragments.BASE_BRANCH})`,
      )
      .eq("customer_id", customerId)
      .eq("merchant_id", merchantId)
      .is("deleted_at", null)
      .not("approved_at", "is", null)
      .order("approved_at", { ascending: false })
      .limit(limit);

    if (params.cursor !== undefined) {
      // Supabase returns timestamptz as ISO; the cursor arrives as ms
      // from the client. Convert at the boundary so the predicate is
      // a real timestamp comparison rather than a string sort.
      query = query.lt(
        "approved_at",
        new Date(params.cursor).toISOString(),
      );
    }

    const { data, error } = await query;
    if (error) {
      throw new Error(
        `Failed to load approved redemptions: ${error.message}`,
      );
    }
    const rows = data ?? [];

    const items: CustomerApprovedRedemption[] = rows.map((row) => {
      const branch = row.branch as unknown as { name: string | null } | null;
      return {
        redemption_id: Number(row.id),
        branch_id: Number(row.branch_id),
        branch_name: branch?.name ?? null,
        amount_redeemed: Number(row.amount_redeemed),
        approved_at: new Date(String(row.approved_at)).getTime(),
      };
    });

    const last = rows[rows.length - 1];
    const nextCursor =
      rows.length === limit && last
        ? new Date(String(last.approved_at)).getTime()
        : null;

    return { items, nextCursor };
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Mutations
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Create a new pending redemption request at (customer, merchant).
   * Calls `redemption_request_create(p_customer_id, p_merchant_id,
   * p_branch_id, p_amount, p_requested_date_ms)` — the RPC generates
   * the code, inserts the audit row, and runs the fan-out atomically.
   *
   * Returns the new audit row (including the generated `redemption_code`).
   * Throws if a pending row already exists at this merchant (the RPC
   * raises P0001) — the route layer surfaces this as a 409.
   */
  async createMyRedemptionRequest(
    customerId: number,
    merchantId: number,
    body: CustomerRedemptionRequestBody,
  ): Promise<CustomerRedemptionRequestResult> {
    return this.runCreateRpc(customerId, merchantId, body);
  }

  /**
   * Edit an existing pending redemption request at (customer, merchant).
   * Calls `redemption_request_update(p_redemption_id, p_amount,
   * p_branch_id)` — the RPC no-ops when amount + branch are unchanged,
   * otherwise hard-deletes the old row + inserts a new one with a
   * fresh code + re-runs the fan-out. Edits don't accumulate
   * soft-deleted rows in the audit table.
   *
   * Returns the resulting audit row (the existing one on no-op, the
   * new one otherwise).
   */
  async updateMyRedemptionRequest(
    customerId: number,
    merchantId: number,
    body: CustomerRedemptionRequestBody,
  ): Promise<CustomerRedemptionRequestResult> {
    const existing = await this.getMyPendingRequest(customerId, merchantId);
    if (!existing) {
      throw new Error("No pending redemption to update");
    }
    const { data, error } = await supabaseAdmin.rpc(
      "redemption_request_update",
      {
        p_redemption_id: existing.redemption_id,
        p_amount: body.amount,
        p_branch_id: body.branchId,
      },
    );
    if (error) {
      throw new Error(`Update failed: ${error.message}`);
    }
    const first = (data ?? [])[0];
    if (!first) {
      throw new Error("Update returned no row");
    }
    return {
      audit_id: Number(first.audit_id),
      redemption_code: Number(first.redemption_code),
      requested_date: Number(first.requested_date),
      branch_id: Number(first.branch_id),
      amount_redeemed: Number(first.amount_redeemed),
      requested_at: String(first.requested_at),
    };
  }

  /**
   * Cancel the customer's pending redemption at (customer, merchant).
   * Calls `redemption_request_cancel(p_redemption_id)` — the RPC
   * hard-deletes the audit row + zeroes the fan-out slices.
   * Idempotent — returns `cancelled: false` when there's no pending
   * row to cancel.
   */
  async cancelMyRedemptionRequest(
    customerId: number,
    merchantId: number,
  ): Promise<{ cancelled: boolean }> {
    const existing = await this.getMyPendingRequest(customerId, merchantId);
    if (!existing) return { cancelled: false };
    const { error } = await supabaseAdmin.rpc("redemption_request_cancel", {
      p_redemption_id: existing.redemption_id,
    });
    if (error) {
      throw new Error(`Cancel failed: ${error.message}`);
    }
    return { cancelled: true };
  }

  // ──────────────────────────────────────────────────────────────────────────
  // Internals
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Run `redemption_request_create` with the customer-supplied
   * `amount` + `branchId`. `requested_date_ms` is `Date.now()` — the
   * migration file's header comment calls out that backend epoch
   * columns are in milliseconds, no `* 1000` / `/ 1000` needed.
   */
  private async runCreateRpc(
    customerId: number,
    merchantId: number,
    body: CustomerRedemptionRequestBody,
  ): Promise<CustomerRedemptionRequestResult> {
    const { data, error } = await supabaseAdmin.rpc(
      "redemption_request_create",
      {
        p_customer_id: customerId,
        p_merchant_id: merchantId,
        p_branch_id: body.branchId,
        p_amount: body.amount,
        p_requested_date_ms: Date.now(),
      },
    );
    if (error) {
      throw new Error(`Create failed: ${error.message}`);
    }
    const first = (data ?? [])[0];
    if (!first) {
      throw new Error("Create returned no row");
    }
    return {
      audit_id: Number(first.audit_id),
      redemption_code: Number(first.redemption_code),
      requested_date: Number(first.requested_date),
      branch_id: Number(first.branch_id),
      amount_redeemed: Number(first.amount_redeemed),
      requested_at: String(first.requested_at),
    };
  }
}

export const customerRedemptionsService = new CustomerRedemptionsService();
