import { supabaseAdmin } from "../utils/supabase.client";
import { QueryFragments } from "../constants/queryFragments";
import {
  CustomerApprovedRedemption,
  CustomerApprovedRedemptionPage,
  CustomerPendingRedemption,
  CustomerRedemptionRequestBody,
  CustomerRedemptionRequestResult,
} from "../types/customerRedemptions.types";

// At most one customer_credit_redemptions row per (customer, merchant) in pending, carrying a 4-digit code generated by the SQL RPC. All writes go through RPCs (redemption_request_create/update/cancel) so the audit-row write + fan-out are atomic.
export class CustomerRedemptionsService {
  async getMyBranches(merchantId: number) {
    const { data, error } = await supabaseAdmin
      .from("branches")
      .select(QueryFragments.BASE_BRANCH)
      .eq("merchant_id", merchantId)
      .is("deleted_at", null)
      .order("name", { ascending: true });
    if (error) {
      throw new Error(`Failed to load branches: ${error.message}`);
    }
    return data ?? [];
  }

  // Returns null when no pending row exists (the route never 404s on "no pending"). redemption_code is customer-only — the merchant service strips it from its response.
  async getMyPendingRequest(
    customerId: number,
    merchantId: number,
  ): Promise<CustomerPendingRedemption | null> {
    const { data, error } = await supabaseAdmin
      .from("customer_credit_redemptions")
      .select(
        `id, customer_id, merchant_id, branch_id, amount_redeemed, redemption_code, requested_date, created_at, branch:branches(${QueryFragments.BASE_BRANCH})`,
      )
      .eq("customer_id", customerId)
      .eq("merchant_id", merchantId)
      .is("deleted_at", null)
      .is("approved_at", null)
      .is("rejected_at", null)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (error) {
      throw new Error(`Failed to load pending request: ${error.message}`);
    }
    if (!data) return null;

    return {
      redemption_code: Number(data.redemption_code),
      redemption_id: Number(data.id),
      branch_id: Number(data.branch_id),
      branch_name: data.branch?.name ?? null,
      amount_redeemed: Number(data.amount_redeemed),
      requested_date: Number(data.requested_date),
      requested_at: String(data.created_at),
    };
  }

  // Cursor-paginated by approved_at DESC (cursor = last item's approved_at ms). nextCursor is the last row's approved_at when the page was exactly limit-sized; null on partial/empty. The 4-digit code is intentionally not returned.
  async getMyApprovedRedemptions(
    customerId: number,
    merchantId: number,
    params: { cursor?: number; limit: number },
  ): Promise<CustomerApprovedRedemptionPage> {
    const limit = Math.min(Math.max(1, params.limit), 50);
    let query = supabaseAdmin
      .from("customer_credit_redemptions")
      .select(
        `id, branch_id, amount_redeemed, approved_at,
         branch:branches(${QueryFragments.BASE_BRANCH})`,
      )
      .eq("customer_id", customerId)
      .eq("merchant_id", merchantId)
      .is("deleted_at", null)
      .not("approved_at", "is", null)
      .order("approved_at", { ascending: false })
      .limit(limit);

    if (params.cursor !== undefined) {
      // Supabase returns timestamptz as ISO; convert the ms cursor at the boundary so the predicate is a real timestamp comparison, not a string sort.
      query = query.lt(
        "approved_at",
        new Date(params.cursor).toISOString(),
      );
    }

    const { data, error } = await query;
    if (error) {
      throw new Error(
        `Failed to load approved redemptions: ${error.message}`,
      );
    }
    const rows = data ?? [];

    const items: CustomerApprovedRedemption[] = rows.map((row) => {
      return {
        redemption_id: Number(row.id),
        branch_id: Number(row.branch_id),
        branch_name: row.branch?.name ?? null,
        amount_redeemed: Number(row.amount_redeemed),
        approved_at: new Date(String(row.approved_at)).getTime(),
      };
    });

    const last = rows[rows.length - 1];
    const nextCursor =
      rows.length === limit && last
        ? new Date(String(last.approved_at)).getTime()
        : null;

    return { items, nextCursor };
  }

  // Throws when a pending row already exists (RPC raises P0001) — the route surfaces this as 409.
  async createMyRedemptionRequest(
    customerId: number,
    merchantId: number,
    body: CustomerRedemptionRequestBody,
  ): Promise<CustomerRedemptionRequestResult> {
    return this.runCreateRpc(customerId, merchantId, body);
  }

  // RPC no-ops when amount+branch unchanged; otherwise hard-deletes the old row + inserts a new one with a fresh code + re-runs the fan-out (edits don't accumulate soft-deleted rows).
  async updateMyRedemptionRequest(
    customerId: number,
    merchantId: number,
    body: CustomerRedemptionRequestBody,
  ): Promise<CustomerRedemptionRequestResult> {
    const existing = await this.getMyPendingRequest(customerId, merchantId);
    if (!existing) {
      throw new Error("No pending redemption to update");
    }
    const { data, error } = await supabaseAdmin.rpc(
      "redemption_request_update",
      {
        p_redemption_id: existing.redemption_id,
        p_amount: body.amount,
        p_branch_id: body.branchId,
      },
    );
    if (error) {
      throw new Error(`Update failed: ${error.message}`);
    }
    const first = (data ?? [])[0];
    if (!first) {
      throw new Error("Update returned no row");
    }
    return {
      audit_id: Number(first.audit_id),
      redemption_code: Number(first.redemption_code),
      requested_date: Number(first.requested_date),
      branch_id: Number(first.branch_id),
      amount_redeemed: Number(first.amount_redeemed),
      requested_at: String(first.requested_at),
    };
  }

  // Idempotent — returns cancelled: false when there's no pending row to cancel.
  async cancelMyRedemptionRequest(
    customerId: number,
    merchantId: number,
  ): Promise<{ cancelled: boolean }> {
    const existing = await this.getMyPendingRequest(customerId, merchantId);
    if (!existing) return { cancelled: false };
    const { error } = await supabaseAdmin.rpc("redemption_request_cancel", {
      p_redemption_id: existing.redemption_id,
    });
    if (error) {
      throw new Error(`Cancel failed: ${error.message}`);
    }
    return { cancelled: true };
  }

  // requested_date_ms is Date.now() — backend epoch columns are in milliseconds, no * 1000 / / 1000 needed.
  private async runCreateRpc(
    customerId: number,
    merchantId: number,
    body: CustomerRedemptionRequestBody,
  ): Promise<CustomerRedemptionRequestResult> {
    const { data, error } = await supabaseAdmin.rpc(
      "redemption_request_create",
      {
        p_customer_id: customerId,
        p_merchant_id: merchantId,
        p_branch_id: body.branchId,
        p_amount: body.amount,
        p_requested_date_ms: Date.now(),
      },
    );
    if (error) {
      throw new Error(`Create failed: ${error.message}`);
    }
    const first = (data ?? [])[0];
    if (!first) {
      throw new Error("Create returned no row");
    }
    return {
      audit_id: Number(first.audit_id),
      redemption_code: Number(first.redemption_code),
      requested_date: Number(first.requested_date),
      branch_id: Number(first.branch_id),
      amount_redeemed: Number(first.amount_redeemed),
      requested_at: String(first.requested_at),
    };
  }
}

export const customerRedemptionsService = new CustomerRedemptionsService();