import { Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useThemeTokens } from "../../../shared/theme/ThemeContext";
import { formatGhs } from "../../../shared/utils/formatGhs";
import {
  customerCreditsService,
  customerRedemptionsService,
} from "../../../api/client";
import { useQuery } from "@tanstack/react-query";
import type {
  CustomerCreditsApiResponse,
  CustomerPendingRedemption,
  CustomerPendingRedemptionApiResponse,
} from "@store-credit-platform/api-services";
import { useMemo } from "react";

const CREDITS_QUERY_KEY = ["customer", "credits"] as const;
const PENDING_REQUEST_KEY = ["customer", "pendingRequest"] as const;

/**
 * "Pending" tab body. After the row-state collapse there is at most one
 * pending request per (customer, merchant) pair — the per-credit
 * breakdown is visible on the Available tab. We render a single
 * rolled-up card showing:
 *   - The requested amount (rolled up from `pending_redemption_amount`
 *     across every live credit at this merchant — the SQL fan-out RPC
 *     updates these slices atomically).
 *   - The 4-digit `redemption_code` generated by the SQL RPC. The
 *     customer shows this to the merchant staff who types it into the
 *     webapp approve dialog.
 *   - The branch the customer picked at request time.
 *   - "Edit request" and "Cancel request" CTAs.
 *
 * Two queries are read:
 *   - `["customer", "credits"]` — drives the amount total + the tab's
 *     loading/error empty state (this is also the source of truth for
 *     "is there a pending row" via the rolled-up total).
 *   - `["customer", "pendingRequest", merchantId]` — drives the
 *     `redemption_code` + branch name display. Returns `data: null`
 *     when the audit row is missing (race with cancel).
 *
 * When the credits query sees a pending total but the audit row has
 * not yet loaded, the card renders the amount + CTAs without a code
 * chip (the code chip appears the moment the audit query resolves).
 */
export function CreditsMerchantPending({
  merchantId,
  merchantName,
  onCancelRequest,
  onEditRequest,
}: {
  merchantId: number;
  merchantName: string;
  onCancelRequest: () => void;
  onEditRequest: () => void;
}) {
  const theme = useThemeTokens();

  const creditsQuery = useQuery<CustomerCreditsApiResponse>({
    queryKey: CREDITS_QUERY_KEY,
    queryFn: () => customerCreditsService.getMyCredits(),
  });

  const pendingQuery = useQuery<CustomerPendingRedemptionApiResponse>({
    // Shares its cache with the parent screen's `pendingQuery` —
    // TanStack de-dupes by queryKey, so the network call only fires
    // once even though both hooks subscribe.
    queryKey: [...PENDING_REQUEST_KEY, merchantId],
    queryFn: () => customerRedemptionsService.getMyPendingRequest(merchantId),
  });

  // Roll up the merchant's `pending_redemption_amount` across every
  // live customer_credit row at this merchant. The credits query
  // returns both `live` and `expired` — pending is always live (the
  // fan-out zero-touches a row on revoke / expire via the auto-shrink
  // trigger), so we only sum live.
  const total = useMemo(() => {
    if (!creditsQuery.data?.success) return 0;
    let sum = 0;
    for (const credit of creditsQuery.data.data.live) {
      if (credit.branch.merchant.id !== merchantId) continue;
      sum += Number(credit.pending_redemption_amount) || 0;
    }
    return sum;
  }, [creditsQuery.data, merchantId]);

  if (creditsQuery.isLoading) {
    return (
      <View style={styles.centerFill}>
        <Text style={{ color: theme.colors.textMuted }}>Loading…</Text>
      </View>
    );
  }
  if (creditsQuery.isError) {
    return (
      <View style={styles.centerFill}>
        <Text
          style={{
            color: theme.colors.textSecondary,
            fontFamily: theme.typography.fontFamilyRegular,
            fontSize: 14,
            textAlign: "center",
          }}
        >
          {creditsQuery.error instanceof Error
            ? creditsQuery.error.message
            : "Couldn't load your pending request."}
        </Text>
      </View>
    );
  }

  if (total <= 0) {
    return (
      <View style={styles.emptyState}>
        <Ionicons
          name="time-outline"
          size={56}
          color={theme.colors.textMuted}
          style={styles.emptyIcon}
        />
        <Text
          style={[
            styles.emptyTitle,
            {
              color: theme.colors.text,
              fontFamily: theme.typography.fontFamilyMedium,
            },
          ]}
        >
          No pending request
        </Text>
        <Text
          style={[
            styles.emptySubtitle,
            {
              color: theme.colors.textSecondary,
              fontFamily: theme.typography.fontFamilyRegular,
            },
          ]}
        >
          You don't have any pending redemption at {merchantName}.
        </Text>
      </View>
    );
  }

  // Pull the code + branch label from the audit-row query when it's
  // loaded. The audit-row query is the sole source for the code — it's
  // only set at request-create time and never leaves the SQL RPC.
  const pendingRow: CustomerPendingRedemption | null = pendingQuery.data
    ?.success
    ? pendingQuery.data.data
    : null;

  return (
    <View style={styles.cardWrap}>
      <PendingCard
        amount={total}
        merchantName={merchantName}
        pendingRow={pendingRow}
        onCancelRequest={onCancelRequest}
        onEditRequest={onEditRequest}
      />
    </View>
  );
}

function PendingCard({
  amount,
  merchantName,
  pendingRow,
  onCancelRequest,
  onEditRequest,
}: {
  amount: number;
  merchantName: string;
  pendingRow: CustomerPendingRedemption | null;
  onCancelRequest: () => void;
  onEditRequest: () => void;
}) {
  const theme = useThemeTokens();

  // The code is a 0-padded 4-digit string. The `redemption_code` RPC
  // returns an integer in [1000, 9999], so we left-pad with zeros to
  // guarantee the visual stays four digits (e.g. "0427" not "427").
  const codeText = pendingRow
    ? String(pendingRow.redemption_code).padStart(4, "0")
    : null;

  const branchLabel = pendingRow?.branch_name ?? null;

  return (
    <View
      style={[
        styles.card,
        {
          backgroundColor: theme.colors.surface,
          borderColor: theme.colors.surfaceBorder,
        },
      ]}
    >
      <Text
        style={[
          styles.eyebrow,
          {
            color: theme.colors.textMuted,
            fontFamily: theme.typography.fontFamilyMedium,
          },
        ]}
      >
        Pending request
      </Text>
      <Text
        style={[
          styles.amount,
          {
            color: theme.colors.text,
            fontFamily: theme.typography.fontFamilyBold,
          },
        ]}
        accessibilityLabel={`Pending ${formatGhs(amount)}`}
      >
        {formatGhs(amount)}
      </Text>

      <View style={styles.codeBlock}>
        <Text
          style={[
            styles.codeEyebrow,
            {
              color: theme.colors.textMuted,
              fontFamily: theme.typography.fontFamilyMedium,
            },
          ]}
        >
          Your code
        </Text>
        {codeText ? (
          <View
            style={[
              styles.codeChip,
              {
                backgroundColor: theme.colors.primary,
              },
            ]}
          >
            <Text
              style={[
                styles.codeText,
                {
                  color: theme.colors.textOnPrimary,
                  fontFamily: theme.typography.fontFamilyBold,
                },
              ]}
              accessibilityLabel={`Redemption code ${codeText}`}
            >
              {codeText}
            </Text>
          </View>
        ) : (
          <View
            style={[
              styles.codeChip,
              styles.codeChipPlaceholder,
              {
                backgroundColor: theme.colors.surfaceInput,
                borderColor: theme.colors.surfaceBorder,
              },
            ]}
          >
            <Text
              style={[
                styles.codeTextPlaceholder,
                {
                  color: theme.colors.textMuted,
                  fontFamily: theme.typography.fontFamilyMedium,
                },
              ]}
            >
              ····
            </Text>
          </View>
        )}

        <Text
          style={[
            styles.caption,
            {
              color: theme.colors.textSecondary,
              fontFamily: theme.typography.fontFamilyRegular,
            },
          ]}
        >
          Share this code with {merchantName} staff to confirm your redemption
          {branchLabel ? ` at ${branchLabel}` : ""}.
        </Text>
      </View>

      <Text
        style={[
          styles.caption,
          {
            color: theme.colors.textSecondary,
            fontFamily: theme.typography.fontFamilyRegular,
          },
        ]}
      >
        Waiting for {merchantName} to confirm. Cancel any time before they
        approve.
      </Text>

      <View style={styles.actionsRow}>
        <Pressable
          onPress={onEditRequest}
          accessibilityRole="button"
          accessibilityLabel="Edit request"
          style={({ pressed }) => [
            styles.actionButton,
            {
              backgroundColor: theme.colors.primary,
              opacity: pressed ? 0.85 : 1,
              borderRadius: theme.radii.sm,
            },
          ]}
        >
          <Text
            style={{
              color: theme.colors.textOnPrimary,
              fontFamily: theme.typography.fontFamilySemiBold,
              fontSize: 13,
              letterSpacing: 0.2,
            }}
          >
            Edit request
          </Text>
        </Pressable>
        <Pressable
          onPress={onCancelRequest}
          accessibilityRole="button"
          accessibilityLabel="Cancel request"
          style={({ pressed }) => [
            styles.actionButton,
            {
              backgroundColor: pressed
                ? theme.colors.surfaceInput
                : theme.colors.surface,
              borderColor: theme.colors.error,
              borderWidth: 1,
              borderRadius: theme.radii.sm,
            },
          ]}
        >
          <Text
            style={{
              color: theme.colors.error,
              fontFamily: theme.typography.fontFamilySemiBold,
              fontSize: 13,
              letterSpacing: 0.2,
            }}
          >
            Cancel request
          </Text>
        </Pressable>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  cardWrap: {
    flex: 1,
    paddingTop: 8,
  },
  card: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 20,
    gap: 8,
  },
  eyebrow: {
    fontSize: 11,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  amount: {
    fontSize: 32,
    letterSpacing: -0.5,
    marginTop: 4,
  },
  caption: {
    fontSize: 13,
    lineHeight: 19,
  },
  codeBlock: {
    alignItems: "center",
    marginVertical: 10,
  },
  codeEyebrow: {
    fontSize: 11,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },

  codeChip: {
    paddingHorizontal: 26,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 30,
    marginTop: 10,
  },

  codeChipPlaceholder: {
    borderWidth: 1,
    borderStyle: "dashed",
  },
  codeText: {
    fontSize: 26,
    letterSpacing: 8,
  },
  codeTextPlaceholder: {
    fontSize: 30,
    letterSpacing: 8,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  actionButton: {
    flex: 1,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  centerFill: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 64,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 48,
    paddingHorizontal: 32,
    gap: 6,
  },
  emptyIcon: {
    marginBottom: 8,
  },
  emptyTitle: {
    fontSize: 18,
    letterSpacing: -0.2,
  },
  emptySubtitle: {
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
});
